[{"ContainerToolsException.Message":"Las herramientas de contenedor de Visual Studio requieren Docker Desktop. Para obtenerlo, consulte https://go.microsoft.com/fwlink/?linkid=847268  Para obtener más información, consulte https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: No se puede ejecutar \"docker-compose\". Compruebe que Docker Desktop está instalado y se está ejecutando localmente. Para solucionar problemas, consulte https://aka.ms/DockerToolsTroubleshooting. ---> System.ComponentModel.Win32Exception: El sistema no puede encontrar el archivo especificado\r\n   en System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)\r\n   en System.Diagnostics.Process.Start()\r\n   en Microsoft.Docker.Utilities.CommandLineClient.<>c__DisplayClass0_0.<ExecuteAsync>b__0() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\Utilities\\CommandLineClient.cs:línea 174\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__15.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:línea 287\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:línea 109\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__33.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:línea 445\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:línea 16\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:línea 82\r\nCódigo de error: DT1001\r\nGravedad: Error\r\nLínea de comandos: docker-compose  -f \"C:\\Users\\carlo\\OneDrive\\Escritorio\\DN6_Carlos_Vazquez\\07_CRUD\\T2\\DataAccess.Example\\docker-compose.yml\" -f \"C:\\Users\\carlo\\OneDrive\\Escritorio\\DN6_Carlos_Vazquez\\07_CRUD\\T2\\DataAccess.Example\\docker-compose.override.yml\" -p dockercompose17234654240583400050 --ansi never kill\r\n"},{"ContainerToolsException.Message":"Las herramientas de contenedor de Visual Studio requieren Docker Desktop. Para obtenerlo, consulte https://go.microsoft.com/fwlink/?linkid=847268  Para obtener más información, consulte https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: No se puede ejecutar \"docker-compose\". Compruebe que Docker Desktop está instalado y se está ejecutando localmente. Para solucionar problemas, consulte https://aka.ms/DockerToolsTroubleshooting. ---> System.ComponentModel.Win32Exception: El sistema no puede encontrar el archivo especificado\r\n   en System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)\r\n   en System.Diagnostics.Process.Start()\r\n   en Microsoft.Docker.Utilities.CommandLineClient.<>c__DisplayClass0_0.<ExecuteAsync>b__0() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\Utilities\\CommandLineClient.cs:línea 174\r\n   --- Fin del seguimiento de la pila de la excepción interna ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__15.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:línea 287\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:línea 109\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__33.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:línea 445\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:línea 16\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:línea 82\r\nCódigo de error: DT1001\r\nGravedad: Error\r\nLínea de comandos: docker-compose  -f \"C:\\Users\\carlo\\OneDrive\\Escritorio\\DN6_Carlos_Vazquez\\07_CRUD\\T2\\DataAccess.Example\\docker-compose.yml\" -f \"C:\\Users\\carlo\\OneDrive\\Escritorio\\DN6_Carlos_Vazquez\\07_CRUD\\T2\\DataAccess.Example\\docker-compose.override.yml\" -p dockercompose17234654240583400050 --ansi never kill\r\n"},{"ContainerToolsException.Message":"Las herramientas de contenedor de Visual Studio requieren que Docker se esté ejecutando antes de compilar, depurar o ejecutar un proyecto con contenedores.  Para obtener más información, consulte https://aka.ms/DockerToolsTroubleshooting","ContainerToolsException.ErrorCode":"","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Ddockercompose17234654240583400050%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified.\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__15.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:línea 287\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:línea 109\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__33.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:línea 445\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.BuildTasks.ComposeDownContainers.<ExecuteCoreAsync>d__4.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\ComposeDownContainers.cs:línea 16\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n   en System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   en Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() en D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:línea 82\r\nCódigo de error: DT1001\r\nGravedad: Error\r\nLínea de comandos: docker-compose  -f \"C:\\Users\\carlo\\OneDrive\\Escritorio\\DN6_Carlos_Vazquez\\07_CRUD\\T2\\DataAccess.Example\\docker-compose.yml\" -f \"C:\\Users\\carlo\\OneDrive\\Escritorio\\DN6_Carlos_Vazquez\\07_CRUD\\T2\\DataAccess.Example\\docker-compose.override.yml\" -p dockercompose17234654240583400050 --ansi never kill\r\nCódigo de salida del comando: 1\r\nSalida del comando: \r\nError de comando: error during connect: this error may indicate that the docker daemon is not running: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?filters=%7B%22label%22%3A%7B%22com.docker.compose.config-hash%22%3Atrue%2C%22com.docker.compose.project%3Ddockercompose17234654240583400050%22%3Atrue%7D%7D\": open //./pipe/docker_engine: The system cannot find the file specified.\r\n"}]